LPAR   = '('
       ;
RPAR   = ')'
       ;
TIMES  = '*'
       ;
SLASH  = '/'
       ;
PLUS   = '+'
       ;
MINUS  = '-'
       ;
AND    = '&&'
       ;
OR     = '||'
       ;
NOT    = '!'
       ;
LT     = '<'
       ;
LTE    = '<='
       ;
GT     = '>'
       ;
GTE    = '>='
       ;
EQ     = '=='
       ;
NEQ    = '!='
       ;
COMMA  = ','
       ;
LCURLY = '{'
       ;
RCURLY = '}'
       ;
NUMBER = ('0'..'9')+ ('.' ('0'..'9')+)?
       ;
IDENT  = (('a'..'Z') | '_')+ ((('a'..'Z') | ('0'-'9') | '_')+)?
       ;
TYPENAME = "int"
         | "float"
         | "string"
         | "bool"
         ;
VARIABLENAME = IDENT (with predicate);
FUNCTIONNAME = IDENT (with predicate);

Atom       = NUMBER
           | LPAR Expression RPAR
           | VARIABLENAME
           | FUNCTIONNAME LPAR (Expression (COMMA Expression)*))? RPAR
           ;

TermNot    = NOT* Atom
           ;
           
TermUnary  = MINUS* TermNot
	   ;
	   
TermMul    = TermUnary
             ((TIMES | SLASH) TermUnary)*
           ;
           
TermAdd    = TermMul
             ((PLUS | MINUS) TermMul)*
           ;
           
TermRel    = TermAdd
             ((LT | LTE | GT | GTE | EQ | NEQ) TermAdd)*
	   ;
	   
Expression = TermRel
             ((AND | OR) TermRel)*
	   ;
	   
VarDecl    = TYPENAME IDENT
             ( EQUALS Expression))?
             SEMICOLON
             ;
            
VarAssign  = VARIABLENAME EQUALS Expression SEMICOLON
           ;
           
Statement = VarDecl
          | VarAssign
          ;

StatementBlock = Statement+
               ;

FunctionDeclaration = TYPENAME IDENT LPAR (TYPENAME IDENT (COMMA TYPENAME IDENT)*)? RPAR
                      LCURLY StatementBlock RCURLY
                    ;
